name = "daprdemo"
main = "worker.ts"
compatibility_date = "2022-12-09"
usage_model = "bundled"

[vars]
PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAyutaN0GSzNkI3N/E/J9aCqpBE/UvLD4pd7tirq5f4tw=
-----END PUBLIC KEY-----
"""
TOKEN_AUDIENCE = "daprdemo"

# Worker defines a binding, named "QUEUE", which gives it a capability
# to send messages to a Queue, named "daprdemo".
[[queues.producers]]
  queue = "daprdemo"
  binding = "daprdemo"

# Worker also receives messages from the Queue, named "daprdemo".
[[queues.consumers]]
  queue = "daprdemo"
  max_batch_size = 10   # Max messages per batch
  max_batch_timeout = 1 # Max seconds to wait before batch is full
  max_retries = 3       # Max retries per batch
