name = "daprdemo"
main = "worker.ts"
compatibility_date = "2022-12-09"
usage_model = "bundled"

[vars]
PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAyutaN0GSzNkI3N/E/J9aCqpBE/UvLD4pd7tirq5f4tw=
-----END PUBLIC KEY-----
"""
TOKEN_AUDIENCE = "daprdemo"

# Worker defines a binding, named "QUEUE", which gives it a capability
# to send messages to a Queue, named "daprdemo".
[[queues.producers]]
  queue = "daprdemo"
  binding = "daprdemo"
