version: "3.5"
services:
  worker:
    build: ./conformance/temporal/worker
    networks:
      - temporal-network
    depends_on:
      - temporal
  postgresql:
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:13
    networks:
      - temporal-network
    ports:
      - 5432:5432
  temporal:
    container_name: temporal
    depends_on:
      - postgresql
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    image: temporalio/auto-setup:1.17.1
    networks:
      - temporal-network
    ports:
      - 7233:7233
    volumes:
      - ./conformance/temporal/server/dynamicconfig:/etc/temporal/config/dynamicconfig
networks:
  temporal-network:
    driver: bridge
    name: temporal-network
