version: '2'
services:
  standalone:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=conf-test-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=conf-test-password
      - DOCKER_INFLUXDB_INIT_ORG=dapr-conf-test
      - DOCKER_INFLUXDB_INIT_BUCKET=dapr-conf-test-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
