version: '2'
services:
  standalone:
    image: apachepulsar/pulsar:2.8.2
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      - BOOKIE_MEM=" -Xms768m -Xms768m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone --advertised-address standalone"
