# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation and Dapr Contributors.
# Licensed under the MIT License.
# ------------------------------------------------------------

FROM daprio/dapr-dev:0.1.5

VOLUME [ "/go/src/github.com/dapr/dapr" ]
