version: '3.8'

services:
  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.5.0
    ports:
      - "8474:8474"  # Toxiproxy API
      - "2222:2222"  # Proxied SFTP port
    environment:
      - HOSTNAME=0.0.0.0
    command: ["-host", "0.0.0.0"]
    volumes:
      - ./toxiproxy.json:/config/toxiproxy.json
    depends_on:
      - sftp
    networks:
      - sftp-network

  sftp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SFTP_USERS=foo:pass:1001:1001:upload
    volumes:
      - ./upload:/home/testuser/upload
    expose:
      - "2222:22"
    networks:
      - sftp-network

networks:
  sftp-network:
    driver: bridge