
# ------------------------------------------------------------
# Copyright 2025 The Dapr Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------

name: Sync release branch to main

on:
  workflow_dispatch:
  push:
    branches:
      - release-*

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing release branch to main
    outputs:
      pr_number: ${{ steps.create_pr.outputs.pr_number }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Create sync PR from release branch to main
      id: create_pr
      uses: tretuna/sync-branches@main
      with:
        GITHUB_TOKEN: ${{ secrets.DAPR_BOT_TOKEN }}
        FROM_BRANCH: ${{ github.ref_name }}
        TO_BRANCH: main
